name: Build and Release IPA
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build IPA and Mac Catalyst
    runs-on: macOS-latest
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        
      - name: Build Swift package
        run: swift build
        
      - name: Run ipabuild.sh
        run: |
          chmod +x ipabuild.sh
          ./ipabuild.sh
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sora-IPA
          path: build/Sora.ipa
          compression-level: 0

      - name: Run macbuild.sh
        run: |
          chmod +x macbuild.sh
          ./macbuild.sh

      - name: Upload Mac Catalyst artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sora-Catalyst
          path: build/Sora-catalyst.zip
          compression-level: 0